### ISSUE TITLE
配合 aria2 on chrome 下载显示错误

### ISSUE THREAD

**Issue by WallBreakerNO4** [guansss/userscripts#1]
配合 aria2 on chrome 下载时，显示 Download error (not_succeeded): USER_CANCELED ，但是实际上aria2是建立了下载的

**Comment by WallBreakerNO4** [comment]
并且下载下来的文件没有改名

**Comment by guansss** [comment]
我看了一下，那个插件会拦截下载任务并直接取消，然后使用自己的下载方案，不遵循文件名

这是那边的问题，无法解决，你可以到那边去提issue

**Comment by WallBreakerNO4** [comment]
> 我看了一下，那个插件会拦截下载任务并直接取消，然后使用自己的下载方案，不遵循文件名
> 
> 这是那边的问题，无法解决，你可以到那边去提issue

OK，知道了
