### ISSUE TITLE
Getting --primary color can be empty, script crashes and doesn't continue

### ISSUE THREAD

**Issue by hme54** [guansss/userscripts#3]
https://github.com/guansss/userscripts/blob/6b7ed7f4da2314f4c85efe143aba02d2954ea78c/userscripts/iwara-enhancement/features/process-teasers.ts#L39

Consistently, `color == ""`, so `adjustAlpha` throws exception and script doesn't continue. Maybe styles not loaded yet when the script runs. Adding `if (!color) return` right after this line seems to work.

**Comment by guansss** [comment]
Didn't notice that, thanks for reporting!

The fix is released.
